 version: '3'

 services:
   db:
      image: 'mcr.microsoft.com/mssql/server'
      container_name: sqlserver
      environment:
        SA_PASSWORD: "sqlserver"
        ACCEPT_EULA: "Y"
      restart: always
      networks: 
       - desafionet
  
   api:
    container_name: desafiobackapi
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      port: 5000
    ports:
      - '5000:80'
    depends_on: 
      - db
    links: 
      - db
    expose:
      - 5000
    networks:
      - desafionet
    restart: always

 networks:
   desafionet:
     name: desafionet