 version: '3'

 services:
   db:
      image: 'mcr.microsoft.com/mssql/server'
      container_name: sqlserver
      environment:
        SA_PASSWORD: "sqlserver"
        ACCEPT_EULA: "Y"
      ports:
        - '1401:1433'
      restart: always
      networks: 
       - desafionet
  
   api:
    container_name: desafiobackapi
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=Server=db,1401;database=master;User Id=sa;Password=sqlserver
    ports:
      - '5001:80'
    depends_on: 
      - db
    links: 
      - db
    expose:
      - 5001
    networks:
      - desafionet
    restart: always

 networks:
   desafionet:
     name: desafionet